run:
  deadline: 5m

linters:
  fast: false
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - exhaustive
    - exportloopref
    - godot
    - gofmt
    - goheader
    - goimports
    - golint
    - govet
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

service:
  golangci-lint-version: 1.32.x # use the fixed version to not introduce new linters unexpectedly
