version: "3.8"
services:
  cobbler:
    image: cobbler-dev
    container_name: cobbler-dev
    volumes:
      - ./cobbler_source:/code
      - ../extracted_iso_image:/extracted_iso_image
    ports:
      - 8081:80
    # We chmod the code, otherwise some files are read-only and cannot be cleaned up:
    command: bash -c "
      /code/docker/develop/scripts/setup-supervisor.sh &&
      chmod -R o+w /code &&
      cobbler import --name Ubuntu-20.04 --breed ubuntu --path /extracted_iso_image/ &&
      tail -F /dev/null
      "
